- name: Clonar repositório do projeto
  ansible.builtin.git:
    repo: "{{ repository_url }}"
    dest: "{{ repo_path }}"
    version: "{{ deploy_branch }}"
    force: yes

- name: Garantir diretório de trabalho do frontend
  ansible.builtin.file:
    path: "{{ app_root }}/frontend"
    state: directory
    owner: "{{ app_user }}"
    group: "{{ app_user }}"
    mode: "0755"

- name: Garantir diretório público do frontend
  ansible.builtin.file:
    path: "{{ frontend_root }}"
    state: directory
    owner: "{{ app_user }}"
    group: "{{ app_user }}"
    mode: "0755"

- name: Copiar frontend para release
  ansible.builtin.copy:
    src: "{{ repo_path }}/front/"
    dest: "{{ app_root }}/frontend"
    owner: "{{ app_user }}"
    group: "{{ app_user }}"
    mode: "0755"
    remote_src: true

- name: Renderizar arquivo de ambiente Vite
  ansible.builtin.template:
    src: env.frontend.j2
    dest: "{{ app_root }}/frontend/.env.production"
    owner: "{{ app_user }}"
    group: "{{ app_user }}"
    mode: "0644"

- name: Instalar dependências frontend
  community.general.npm:
    path: "{{ app_root }}/frontend"
    production: false

- name: Build Vite
  ansible.builtin.command:
    cmd: npm run build
    chdir: "{{ app_root }}/frontend"

- name: Publicar artefatos no Nginx
  ansible.builtin.copy:
    src: "{{ app_root }}/frontend/dist/"
    dest: "{{ frontend_root }}
    owner: "{{ app_user }}"
    group: "{{ app_user }}"
    mode: "0755"
    remote_src: true
